# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8795cc3f782206502c6ef8b2fe198831f208e2119a2a280d8d60f8d9639801471ba733be71c0648a2a728d6eb4f1d7c4c4c6b0138aa1e17e37715beec15ebc2

test:
  secret_key_base: 34bf234a1b1edc35ffa66a4890c69b69d496fe5762982d40c56d0176ba0539426c4ef527514d395acfc6155df847f4c21dc9769f89430406495f097115cb6232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
